name: Get Bing Daily Wallpaper

on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run
      run: |
        python main.py
    - name: Git commit and push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Add new image"
        git push

