name: 获取必应每日壁纸

on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get_bing_daily_wallpaper:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 配置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 运行脚本
      run: |
        python main.py

    - name: 提交代码
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Add new image"
        git push

